# Generated by Django 6.0 on 2025-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('stock_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('trim', models.CharField(blank=True, max_length=100)),
                ('body_style', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('mileage', models.IntegerField(help_text='Current mileage in km')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('SERVICE', 'In Service')], default='AVAILABLE', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='vehicles/')),
            ],
        ),
    ]
