import os
import django

# Setup Django Environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'auto_crm.settings')
django.setup()

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from inventory.models import Vehicle
from sales.models import Lead

User = get_user_model()

def setup():
    print("Creating User Groups...")

    # 1. Create Groups
    manager_group, _ = Group.objects.get_or_create(name='Manager')
    sales_group, _ = Group.objects.get_or_create(name='Sales')

    # 2. Get Permissions (Standard Django Logic)
    # We want Sales to VIEW vehicles but NOT delete them
    vehicle_ct = ContentType.objects.get_for_model(Vehicle)
    lead_ct = ContentType.objects.get_for_model(Lead)

    # Note: These codenames are auto-generated by Django: 'view_modelname', 'add_modelname', etc.
    try:
        view_vehicle = Permission.objects.get(content_type=vehicle_ct, codename='view_vehicle')
        add_lead = Permission.objects.get(content_type=lead_ct, codename='add_lead')
        view_lead = Permission.objects.get(content_type=lead_ct, codename='view_lead')
        
        # 3. Assign Permissions to Sales Group
        sales_group.permissions.add(view_vehicle, add_lead, view_lead)
        print("Sales Group Configured (View Only + Add Leads)")
    except Permission.DoesNotExist:
        print("⚠️ Warning: Could not find specific permissions. Run 'python manage.py migrate' first.")

    # 4. Create MANAGER User
    if not User.objects.filter(username='manager').exists():
        u = User.objects.create_superuser('manager', 'manager@apex.com', 'admin123')
        # --- CRITICAL: Set Custom Fields ---
        u.is_manager = True
        u.is_sales = True
        u.save()
        print("Created Superuser: manager / admin123")
    else:
        # Update existing manager
        u = User.objects.get(username='manager')
        u.is_manager = True
        u.is_sales = True
        u.save()
        print("Updated existing user: manager")

    # 5. Create SALES User
    if not User.objects.filter(username='sales').exists():
        u = User.objects.create_user('sales', 'sales@apex.com', 'sales123')
        sales_group.user_set.add(u)
        # --- CRITICAL: Set Custom Fields ---
        u.is_manager = False
        u.is_sales = True
        u.save()
        print("Created User: sales / sales123")
    else:
        # Update existing sales user
        u = User.objects.get(username='sales')
        u.is_manager = False
        u.is_sales = True
        sales_group.user_set.add(u) # Ensure they are in the group too
        u.save()
        print("Updated existing user: sales")

    print("✅ Roles & Users Setup Complete!")

if __name__ == '__main__':
    setup()