# Generated by Django 6.0 on 2025-12-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('has_trade_in', models.BooleanField(default=False)),
                ('trade_in_make', models.CharField(blank=True, max_length=50)),
                ('trade_in_model', models.CharField(blank=True, max_length=50)),
                ('trade_in_year', models.IntegerField(blank=True, null=True)),
                ('trade_in_mileage', models.IntegerField(blank=True, null=True)),
                ('estimated_trade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interested_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inventory.vehicle')),
            ],
        ),
    ]
