# Generated by Django 6.0 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='estimated_trade_value',
            new_name='down_payment',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='trade_in_mileage',
            new_name='term_months',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='interested_vehicle',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_rep',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='has_trade_in',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='trade_in_make',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='trade_in_model',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='trade_in_year',
        ),
        migrations.AddField(
            model_name='lead',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('TEST_DRIVE', 'Test Drive'), ('NEGOTIATION', 'Negotiation'), ('SOLD', 'Sold'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
