# Generated by Django 6.0 on 2025-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_estimated_trade_value_lead_down_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Walk-in', 'Walk-in'), ('Facebook', 'Facebook'), ('Google', 'Google'), ('Referral', 'Referral'), ('Website', 'Website')], default='Walk-in', max_length=50),
        ),
    ]
