# Generated by Django 6.0 on 2025-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='cost',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
