# Generated by Django 6.0 on 2025-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_servicerecord_cost_alter_servicerecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
